@startuml

title Router go back

:Msg::GoBack;

:fn update;

:request_moving_back;

if(previous_route) then (exists)
    :router.move = move_back;
    :notify subs::UrlRequested;
else
:nothing to do;
endif
:router_listening;
@enduml

