@startuml

title Router listening

:fn init
 __router() __
.init(url)
.subscribe(sub_handle)
;
note right
   register subscribe_handle
   //call back with __confirm_navigation(url)__// on requested_url
end note



:subs::UrlRequested(requested_url,_);
:router().confirm_navigation(url);
:match router move;

split
 :navigate to next;

if (route?) then (exist)
        :current_route = route;
    else (not found)
        :current_route = default_route;
    endif
    :update history;
split again
 :move back;
split again
 :move forward;
end split

:router : is_ready;
@enduml
